owner: jedahan # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

status-website: # Status website (optional)
  cname: uptime.jedahan.com # Custom domain CNAME
  name: uptime # Status website title
  
sites:
  - name: jedahan.com
    url: https://jedahan.com
  - name: jonathan.is
    url: https://jonathan.is
  - name: woodbine.nyc
    url: https://woodbine.nyc
  - name: basement.woodbine.nyc
    url: https://basement.woodbine.nyc
